# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1P72aE49FRZL6rnpCYq4EOVQthH8h9S
"""


import gradio as gr
import numpy as np
from PIL import Image
from transformers import AutoProcessor, BlipForConditionalGeneration

processor = AutoProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

def caption_image(input_image: np.ndarray):
    # Convert numpy array to PIL Image and convert to RGB
    raw_image = Image.fromarray(input_image).convert('RGB')

    # Process the image
    inputs = processor(raw_image,return_tensors="pt")


    # Generate a caption for the image
    out = model.generate(**inputs,max_new_tokens=50)


    # Decode the generated tokens to text and store it into `caption`
    caption = processor.decode(out[0],skip_special_token = True)

    return caption

iface = gr.Interface(
  fn=caption_image,
  inputs=gr.Image(),
  outputs="text",
  title="Image Captioning",
  description="This is a simple web app for generating captions for images using a trained model."
)

iface.launch(debug=True,share = True)

