# -*- coding: utf-8 -*-
"""Blip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkiRKn99juglhXL1DH62vv_7eKKMTDSP
"""

import requests
from PIL import Image
from transformers import AutoProcessor, BlipForConditionalGeneration

# Load the pretrained processor and model
processor = AutoProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# Load your image, DONT FORGET TO WRITE YOUR IMAGE NAME
img_path = r"D:\Downloads\a_youtube_thumbnail_still_more_like_a.jpeg"
# convert it into an RGB format
image = Image.open(img_path).convert('RGB')

# You do not need a question for image captioning
text = "the image of"
inputs = processor(images=image, text=text, return_tensors="pt")

# Generate a caption for the image
outputs = model.generate(**inputs, max_length=50)

# Decode the generated tokens to text
caption = processor.decode(outputs[0], skip_special_tokens=True)
# Print the caption
print(caption)

